### ISSUE TITLE
How to properly input proxies

### ISSUE THREAD

**Issue by imdylan0831** [shahzain345/Discord-MultiToolPY#11]
I have my own proxylist. The problem being I don't know how to actually make the tool use those because it does not connect properly to the proxies in the list, even though most of them are working. How do I correctly input the proxies in the txt. file?

**Comment by shahzain345** [comment]
The proxies should be in this format:
Format for proxies with auth
```txt
username:pass@ip:port
username:pass@ip:port
```
Format for proxies without auth
```txt
ip:port
```
I hope this helps!

**Comment by imdylan0831** [comment]
thank you this is very helpful. though if i can ask another question in this thread (so as to not clutter the issues section). how do i deal with the member scrape not working when members of the server have nonlatin names?
