### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by NotASkidder** [shahzain345/Discord-MultiToolPY#6]
idk when i put join server it puts me this
Expecting value: line 1 column 1 (char 0)

same for my friend

**Comment by shahzain345** [comment]
Could you please send a screenshot of the issue?

**Comment by NotASkidder** [comment]
![Immagine 2022-07-06 145740](https://user-images.githubusercontent.com/81571063/177555897-a4a2c3c3-316f-4124-945e-b6c585ca3927.png)

its so weird, it worked but when the tool updated i reinstall it and this error popped
thanks for the help

**Comment by NotASkidder** [comment]
in the guilded someone got same error, and also my friend got it, so it is fixable

**Comment by shahzain345** [comment]
Fixed!
