### ISSUE TITLE
currently patched

### ISSUE THREAD

**Issue by skiddiegit** [shahzain345/Discord-MultiToolPY#7]
currently i tried with checker and it gives me all invalid when they are not, 
and in joiner it gives:
Illegal header value b'OTY1OTMxNTUxMjQwMTEwMTAw.Yl6X_g.l2jskjXBjp9YcOy2SfruQnOwOmY '

so yea discord patched all the tools, we would really like if you unpatch this like vanshaj did, because you are really helping us to raid server with this tool, and so if you fix it im sure i will give you a little donation.
keep it up

**Comment by p3tt3** [comment]
> 

put token whitout "" or ''

**Comment by shahzain345** [comment]
Yep, i have noticed this problem, I am working on a fix with a couple of new features that are 🔥.
