### ISSUE TITLE
token joiner patched

### ISSUE THREAD

**Issue by p3tt3** [shahzain345/Discord-MultiToolPY#8]
the token joiner now it's patched because discord added new tokens and this joiner don't support

when release date new update with option fixed?

**Comment by MOIJESUIS2ENMOI** [comment]
Discord patched new joiner(updated 2 weeks ago) two days ago and for the moment no solution found:
This is the things that is probably used to detect bots:
-X-context-properties 
-X-super-properties
-New cookies

In the headers

**Comment by p3tt3** [comment]
> Discord patched new joiner(updated 2 weeks ago) two days ago and for the moment no solution found: This is the things that is probably used to detect bots: -X-context-properties -X-super-properties -New cookies
> 
> In the headers

So of I change the headers the joiner work again?

**Comment by MOIJESUIS2ENMOI** [comment]
Yes I think that the patch come from the headers like 2 weeks ago, idk which thing is now checked by discord but I am working on it... 
Maybe X-context-properties to encode with right informations from the previous get request with all invite informations, because x-super-properties is based on the device. Or new cookies. 
I saw that dmdgo was also patched (for the sames reasons)

**Comment by p3tt3** [comment]
> Yes I think that the patch come from the headers like 2 weeks ago, idk which thing is now checked by discord but I am working on it... Maybe X-context-properties to encode with right informations from the previous get request with all invite informations, because x-super-properties is based on the device. Or new cookies. I saw that dmdgo was also patched (for the sames reasons)

Ok, thank you for the informations

**Comment by shahzain345** [comment]
I have done some research on this myself, and it seems like the problem is caused by the `user-agent` header and the `x-super-properties` header, the `x-context-properties` header has nothing to do with this. I'm working on a fix where you can either add the `x-super-properties` header in your config.json file or the tool will automatically create a random one

**Comment by p3tt3** [comment]
> 

Ok thank you for your hard work

**Comment by MOIJESUIS2ENMOI** [comment]
super work! You mean that discord check if the informations in the `x-super-properties` is the same as the `user-agent `, that's logic...

**Comment by p3tt3** [comment]
> I have done some research on this myself, and it seems like the problem is caused by the `user-agent` header and the `x-super-properties` header, the `x-context-properties` header has nothing to do with this. I'm working on a fix where you can either add the `x-super-properties` header in your config.json file or the tool will automatically create a random one

When release date of new update?

**Comment by MOIJESUIS2ENMOI** [comment]
I tried with:
 `headers = {
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "origin": "https://discord.com",
    "referer": "https://discord.com/channels/@me",
    "sec-ch-ua": '" Not;A Brand";v="99", "Microsoft Edge";v="103", "Chromium";v="103"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71",
    "x-context-properties": "eyJsb2NhdGlvbiI6IkpvaW4gR3VpbGQiLCJsb2NhdGlvbl9ndWlsZF9pZCI6Ijg3NTA5ODM0MjM3ODU5NDM2NSIsImxvY2F0aW9uX2NoYW5uZWxfaWQiOiI4NzUxMDA5NzQ1OTM3NDkwMTQiLCJsb2NhdGlvbl9jaGFubmVsX3R5cGUiOjB9",
    "x-debug-options": "bugReporterEnabled",
    "x-discord-locale": "en-US",
    "x-super-properties": "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwic3lzdGVtX2xvY2FsZSI6ImVuLVVTIiwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMy4wLjUwNjAuMTM0IFNhZmFyaS81MzcuMzYgRWRnLzEwMy4wLjEyNjQuNzEiLCJicm93c2VyX3ZlcnNpb24iOiIxMDMuMC41MDYwLjEzNCIsIm9zX3ZlcnNpb24iOiIxMCIsInJlZmVycmVyIjoiIiwicmVmZXJyaW5nX2RvbWFpbiI6IiIsInJlZmVycmVyX2N1cnJlbnQiOiIiLCJyZWZlcnJpbmdfZG9tYWluX2N1cnJlbnQiOiIiLCJyZWxlYXNlX2NoYW5uZWwiOiJzdGFibGUiLCJjbGllbnRfYnVpbGRfbnVtYmVyIjoxMzg3MzQsImNsaWVudF9ldmVudF9zb3VyY2UiOm51bGx9"
}`
as headers and this code for cookies and this for the super properties I add later to the code:
`data = {
    "os": "Windows",
    "browser": "Chrome",
    "device": "",
    "system_locale": "en-US",
    "browser_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71",
    "browser_version": "103.0.5060.134",
    "os_version": "10",
    "referrer": "",
    "referring_domain": "",
    "referrer_current": "",
    "referring_domain_current": "",
    "release_channel": "stable",
    "client_build_number": 138734,
    "client_event_source": None
}

def getSuperproperties(data):
    poperties = base64.b64encode(json.dumps(data).encode()).decode()
    return poperties`

and discord return me "You need to update your app to join the server", but the build number is the last ;(
Any ideas?

**Comment by p3tt3** [comment]
> 

Try update your discord app or your browser

**Comment by MOIJESUIS2ENMOI** [comment]
it's the lastest build from my browser... It's for patching discord patch...

**Comment by shahzain345** [comment]
> I tried with:
> 
>  `headers = {
> 
>     "accept": "*/*",
> 
>     "accept-encoding": "gzip, deflate, br",
> 
>     "accept-language": "en-US,en;q=0.9",
> 
>     "content-type": "application/json",
> 
>     "origin": "https://discord.com",
> 
>     "referer": "https://discord.com/channels/@me",
> 
>     "sec-ch-ua": '" Not;A Brand";v="99", "Microsoft Edge";v="103", "Chromium";v="103"',
> 
>     "sec-ch-ua-mobile": "?0",
> 
>     "sec-ch-ua-platform": '"Windows"',
> 
>     "sec-fetch-dest": "empty",
> 
>     "sec-fetch-mode": "cors",
> 
>     "sec-fetch-site": "same-origin",
> 
>     "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71",
> 
>     "x-context-properties": "eyJsb2NhdGlvbiI6IkpvaW4gR3VpbGQiLCJsb2NhdGlvbl9ndWlsZF9pZCI6Ijg3NTA5ODM0MjM3ODU5NDM2NSIsImxvY2F0aW9uX2NoYW5uZWxfaWQiOiI4NzUxMDA5NzQ1OTM3NDkwMTQiLCJsb2NhdGlvbl9jaGFubmVsX3R5cGUiOjB9",
> 
>     "x-debug-options": "bugReporterEnabled",
> 
>     "x-discord-locale": "en-US",
> 
>     "x-super-properties": "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwic3lzdGVtX2xvY2FsZSI6ImVuLVVTIiwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMy4wLjUwNjAuMTM0IFNhZmFyaS81MzcuMzYgRWRnLzEwMy4wLjEyNjQuNzEiLCJicm93c2VyX3ZlcnNpb24iOiIxMDMuMC41MDYwLjEzNCIsIm9zX3ZlcnNpb24iOiIxMCIsInJlZmVycmVyIjoiIiwicmVmZXJyaW5nX2RvbWFpbiI6IiIsInJlZmVycmVyX2N1cnJlbnQiOiIiLCJyZWZlcnJpbmdfZG9tYWluX2N1cnJlbnQiOiIiLCJyZWxlYXNlX2NoYW5uZWwiOiJzdGFibGUiLCJjbGllbnRfYnVpbGRfbnVtYmVyIjoxMzg3MzQsImNsaWVudF9ldmVudF9zb3VyY2UiOm51bGx9"
> 
> }`
> 
> as headers and this code for cookies and this for the super properties I add later to the code:
> 
> `data = {
> 
>     "os": "Windows",
> 
>     "browser": "Chrome",
> 
>     "device": "",
> 
>     "system_locale": "en-US",
> 
>     "browser_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71",
> 
>     "browser_version": "103.0.5060.134",
> 
>     "os_version": "10",
> 
>     "referrer": "",
> 
>     "referring_domain": "",
> 
>     "referrer_current": "",
> 
>     "referring_domain_current": "",
> 
>     "release_channel": "stable",
> 
>     "client_build_number": 138734,
> 
>     "client_event_source": None
> 
> }`
> 
> 
> 
> `def getSuperproperties(data):
> 
>     poperties = base64.b64encode(json.dumps(data).encode()).decode()
> 
>     return poperties`
> 
> 
> 
> and discord return me "You need to update your app to join the server", but the build number is the last ;(
> 
> Any ideas?

What http client are you using. Httpx?

**Comment by MOIJESUIS2ENMOI** [comment]
I am using requests…

**Comment by shahzain345** [comment]
And also try getting the headers from a non-chromium based browser or discord client(not the pc one because its electron based which is technically a chromium tab running the app), use a browser like Firefox or Safari, they are not based on the chromium project. Most of the browsers these days are based onto chromium, i.e: Google Chrome, Microsoft Edge, Opr(Opera), Opera GX, Brave Browser and etc.

**Comment by MOIJESUIS2ENMOI** [comment]
Thank you very much for this information, I will try with safari and Firefox. And maybe with different x-super-properties informations…

**Comment by shahzain345** [comment]
> I am using requests…

I suggest you use httpx, requests is considered "patched", I mean you could get it to work by modifying the TLS Config but I would suggest against it, because you can just use `httpx` without modifying anything, and both of them are very similar feature-wise.

**Comment by MOIJESUIS2ENMOI** [comment]
You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻

**Comment by p3tt3** [comment]
> You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻

Do you know how to make a discord thread spammer?
Because I Need It lmao

**Comment by MOIJESUIS2ENMOI** [comment]
> > You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻
> 
> Do you know how to make a discord thread spammer? Because I Need It lmao

What do you mean? Spamming mentions and messages in all channels? If the account joined the server I can do it. 
For the moment, I think that my joiner is blocked due to captcha bypass(idk why lmao)… 
Did you find a working token joiner?

**Comment by p3tt3** [comment]
> > > You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻
> > 
> > 
> > Do you know how to make a discord thread spammer? Because I Need It lmao
> 
> What do you mean? Spamming mentions and messages in all channels? If the account joined the server I can do it. For the moment, I think that my joiner is blocked due to captcha bypass(idk why lmao)… Did you find a working token joiner?

No,I mean a discord thread spammer(https://discord.com/api/v9/channels/YOUR CHANNEL ID/threads)I want to make a spammer for threads option on discord

**Comment by MOIJESUIS2ENMOI** [comment]
> > > > You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻
> > > 
> > > 
> > > Do you know how to make a discord thread spammer? Because I Need It lmao
> > 
> > 
> > What do you mean? Spamming mentions and messages in all channels? If the account joined the server I can do it. For the moment, I think that my joiner is blocked due to captcha bypass(idk why lmao)… Did you find a working token joiner?
> 
> No,I mean a discord thread spammer(https://discord.com/api/v9/channels/YOUR CHANNEL ID/threads)I want to make a spammer for threads option on discord

And what the spammer will exactly do in the thread?

**Comment by p3tt3** [comment]
> > > > > You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻
> > > > 
> > > > 
> > > > Do you know how to make a discord thread spammer? Because I Need It lmao
> > > 
> > > 
> > > What do you mean? Spamming mentions and messages in all channels? If the account joined the server I can do it. For the moment, I think that my joiner is blocked due to captcha bypass(idk why lmao)… Did you find a working token joiner?
> > 
> > 
> > No,I mean a discord thread spammer(https://discord.com/api/v9/channels/YOUR CHANNEL ID/threads)I want to make a spammer for threads option on discord
> 
> And what the spammer will exactly do in the thread?

Tell me your discord,so I can dm you

**Comment by MOIJESUIS2ENMOI** [comment]
> > > > > > You mean that requests has something like a fingerprint? I will see to change my requests for https. Thank you very much for theses information 🙏🏻
> > > > > 
> > > > > 
> > > > > Do you know how to make a discord thread spammer? Because I Need It lmao
> > > > 
> > > > 
> > > > What do you mean? Spamming mentions and messages in all channels? If the account joined the server I can do it. For the moment, I think that my joiner is blocked due to captcha bypass(idk why lmao)… Did you find a working token joiner?
> > > 
> > > 
> > > No,I mean a discord thread spammer(https://discord.com/api/v9/channels/YOUR CHANNEL ID/threads)I want to make a spammer for threads option on discord
> > 
> > 
> > And what the spammer will exactly do in the thread?
> 
> Tell me your discord,so I can dm you

Moijesuis2enmoi#5278
